### ISSUE TITLE
Licences API (gam info user) traceback errors - not sure if temporary or ongoing

### ISSUE THREAD

**Issue by KatBillington** [taers232c/GAMADV-XTD3#100]
Hi,

Had this error start popping up today, I suspect it's a change at google's end on the licensing API or subdomain.

I updated to latest GAM version and still recurring 
Did a Service account check.  It initially failed, added cloud identity API and waited for it to pass and still recurring
Replicated across multiple g-suites

$ gam info user username
Traceback (most recent call last):
  File "gam.py", line 48720, in ProcessGAMCommand
  File "gam.py", line 27712, in doInfoUser
  File "gam.py", line 27447, in infoUsers
  File "googleapiclient/_helpers.py", line 134, in positional_wrapper
  File "googleapiclient/http.py", line 1524, in execute
  File "googleapiclient/http.py", line 1458, in _execute
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://licensing.googleapis.com/batch returned "Not Found">

$ gam info user users nolicences
Works as expected

Love the app,
Cheers

**Comment by KatBillington** [comment]
Sorry, just checked the groups and saw it's a known issue.  In the meantime if you ever felt like changing it, I would vote in favour of 'nolicences' being the default call and needing to add a 'licences' flag to include the secondary call.
