### ISSUE TITLE
notify <email> doesn't work 

### ISSUE THREAD

**Issue by kk-x** [taers232c/GAMADV-XTD3#16]
Traceback (most recent call last):
  File "gam.py", line 40960, in ProcessGAMCommand
  File "gam.py", line 22167, in doCreateUser
  File "gam.py", line 8285, in sendCreateUpdateUserNotification
KeyError: 'primaryEmail'

After the 4.88.04 update - this is the error message

**Comment by taers232c** [comment]
Should be fixed in 4.88.05

**Comment by kk-x** [comment]
Brilliant work. Confirmed working in 4.88.05.

Thanks
