### ISSUE TITLE
Error running update chromepolicy

### ISSUE THREAD

**Issue by jenglert-qns** [taers232c/GAMADV-XTD3#229]
When I try to update the chrome.users.UrlBlocking policy, I'm getting a throwback

gam update chromepolicy chrome.users.UrlBlocking urlBlockList "https://cnn.com" orgunit "/APITEST"

Traceback (most recent call last):
  File "__init__.py", line 59078, in ProcessGAMCommand
  File "__init__.py", line 21461, in doUpdateChromePolicy
  File "__init__.py", line 21349, in buildChromeSchemas
KeyError: 'description'

I'm running v6.13.08

**Comment by taers232c** [comment]
I'm working on the fix.
--
***@***.***

**Comment by taers232c** [comment]
Fixed in 6.13.09

**Comment by jenglert-qns** [comment]
Works like a charm! Thanks!
