### ISSUE TITLE
Not able to enable GAMADV-XTD3 client access

### ISSUE THREAD

**Issue by Hcsmarnold** [taers232c/GAMADV-XTD3#257]
Once I select Continue to authorization and allow in the web browser the browser times out and redirects to 127.0.0.1:8080 and I get an error in the console. 
`If you use a browser on another computer, you will get a browser error that the site can't be reached AFTER you
click the Allow button, paste "Unable to connect" URL from other computer (only URL data up to &scope required):

Enter verification code or paste "Unable to connect" URL from other computer (only URL data up to &scope required): Process Process-2:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 315, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "__init__.py", line 8983, in _waitForHttpClient
AttributeError: 'NoneType' object has no attribute 'replace'
Traceback (most recent call last):
  File "__init__.py", line 61066, in ProcessGAMCommand
  File "__init__.py", line 60156, in processOauthCommands
  File "__init__.py", line 9369, in doOAuthCreate
  File "__init__.py", line 9323, in doOAuthRequest
  File "__init__.py", line 9226, in from_client_secrets
  File "__init__.py", line 9019, in run_dual
  File "<string>", line 2, in __getitem__
  File "multiprocessing\managers.py", line 833, in _callmethod
KeyError: 'code'`

**Comment by taers232c** [comment]
Send me a Meet/Zoom invitation.

Ross
--
ross.scroggs @ gmail.com
