### ISSUE TITLE
Displaying chromeschemas results in TypeError

### ISSUE THREAD

**Issue by mattfippard** [taers232c/GAMADV-XTD3#310]
Running the command `gam show chromeschemas` results in an error while displaying the entry below. This happens every time so I can't see any policies beyond the 7th entry.  I don't think I have this policy configured anywhere but I'm sure I shouldn't be getting an error from it either way.

```
Chrome Policy Schema: customers/C0300tw6w/policySchemas/chrome.users.appsconfig.BlockExtensionsByPermission (7/721)
    categoryTitle: Additional application settings
    definition:
      messageType:
        field:
          label: LABEL_REPEATED
            name: extensionBlockedPermissions
            number: 1
            type: TYPE_STRING
          label: LABEL_REPEATED
            name: runtimeBlockedHosts
            number: 2
            type: TYPE_STRING
          label: LABEL_REPEATED
            name: runtimeAllowedHosts
            number: 3
            type: TYPE_STRING
          name: BlockExtensionsByPermission
    fieldDescriptions:
Traceback (most recent call last):
  File "__init__.py", line 64792, in ProcessGAMCommand
  File "__init__.py", line 23748, in doPrintShowChromeSchemas
  File "__init__.py", line 23655, in _showChromePolicySchema
  File "__init__.py", line 8102, in showJSON
  File "__init__.py", line 8075, in _show
  File "__init__.py", line 8058, in _show
  File "__init__.py", line 8075, in _show
  File "__init__.py", line 8092, in _show
  File "__init__.py", line 2565, in printJSONValue
  File "__init__.py", line 516, in formatKeyValueList
TypeError: can only concatenate str (not "NoneType") to str
      defaultValue:
```

**Comment by mattfippard** [comment]
`gam print chromeschemas todrive` successful so it's not a problem with the policy itself
