### ISSUE TITLE
Error adding drivefileacls

### ISSUE THREAD

**Issue by damionwilliams** [taers232c/GAMADV-XTD3#396]
Hi Ross,

I hope you're well!

Seeing this error while trying to update drive file acls today:

gam create drivefileacl 0AB5M7XXXXxYcUk9PVA user damionwilliams@domain.com role organizer
Traceback (most recent call last):
  File "__init__.py", line 73046, in ProcessGAMCommand
  File "__init__.py", line 60278, in doCreateDriveFileACL
    'bcc': 'Bcc',
  File "__init__.py", line 60193, in createDriveFileACL
    pageMessage=getPageMessage(), maxItems=parameters['maxItems'],
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "__init__.py", line 52540, in _validatePermissionOwnerType
    def transferDrive(users):
                   ^^^^^^^^^^^
TypeError: unsupported operand type(s) for -: 'str' and 'set'

gam user damionwilliams@domain.com add drivefileacl 1hjZ3RkLE_x4PeEKwPTwlK__MxiD-LNI user test-user-101@domain.com role reader
Traceback (most recent call last):
  File "__init__.py", line 73072, in ProcessGAMCommand
  File "__init__.py", line 60193, in createDriveFileACL
    pageMessage=getPageMessage(), maxItems=parameters['maxItems'],
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "__init__.py", line 52540, in _validatePermissionOwnerType
    def transferDrive(users):
                   ^^^^^^^^^^^
TypeError: unsupported operand type(s) for -: 'str' and 'set'

Using GAMADV-XTD3 6.68.02 on Windows

Thank you as always for your work on this tool,
Damion

**Comment by damionwilliams** [comment]
You're a star thank you Ross!
