### ISSUE TITLE
[8396] Failed to execute script 'pyi_rth_win32comgenpy' due to unhandled exception!

### ISSUE THREAD

**Issue by atp-jiormillada** [taers232c/GAMADV-XTD3#402]
Hi, I am a newbie using GAMADV-XTD3.
I tried to install this in one of my remote servers so that I can use it to automate GWS stuff.
It's working just last week but suddenly just today it is not.

Here's the error code upon code execution:

```
Traceback (most recent call last):
  File "PyInstaller\hooks\rthooks\pyi_rth_win32comgenpy.py", line 46, in <module>
  File "PyInstaller\hooks\rthooks\pyi_rth_win32comgenpy.py", line 25, in _pyi_rthook
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "win32com\__init__.py", line 8, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "pythoncom.py", line 2, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "pywintypes.py", line 126, in <module>
  File "pywintypes.py", line 116, in __import_pywin32_system_module__
ImportError: DLL load failed while importing pywintypes: The parameter is incorrect.
[8396] Failed to execute script 'pyi_rth_win32comgenpy' due to unhandled exception!
```

**Comment by taers232c** [comment]
I'm in California (PDT) and am generally available starting at 7:30AM

I'm available now (7:55PM PDT) for abouth 30 minutes; if you're availa, send me a Meet/Zoom invitation.

Ross
----
Ross Scroggs
***@***.***
