### ISSUE TITLE
Vault count errors not reported correctly

### ISSUE THREAD

**Issue by archierosenblum** [taers232c/GAMADV-XTD3#433]
When getting vault counts for a large number of users with large mailboxes using gam 6.80.11, the errors come back as a separate json rows, and the rows with the email shows a count of 0 (which is not correct) and no data in the error field.

The users below have over 250k emails in the vault.  The desired outcome is that error field next to the email would contain the contain the error, and there would be no json rows.

`gam print vaultcounts todrive matter "id:<matter id>" corpus mail scope all_data everyone `

<img width="569" alt="image" src="https://github.com/user-attachments/assets/5eee67da-86a1-4356-9f47-c3baa3958826">

**Comment by taers232c** [comment]
Send me a Meet/Zoom invitation and we'll investigate

Ross
----
Ross Scroggs
***@***.***

**Comment by taers232c** [comment]
Archie,

I believe that this is fixed in 6.80.12

Ross
----
Ross Scroggs
***@***.***

**Comment by archierosenblum** [comment]
Ross, thank you for looking into this issue.   On 6.80.15, it is hitting an exception every time:

```
MacBookPro ~ % gam print vaultcounts todrive matter "id:4627529a-a849-46fc-9dd7-2ffc145b5cee" corpus mail scope all_data everyone
Getting all Vault Matter Artifacts for Vault Operation: operations/count/a3f96b4a-969a-4ec7-aa8e-937e6449a6eb, may take some time on a large Vault Matter...
Vault Operation: operations/count/a3f96b4a-969a-4ec7-aa8e-937e6449a6eb, Is not done, checking again in 15 seconds
Vault Operation: operations/count/a3f96b4a-969a-4ec7-aa8e-937e6449a6eb, Is not done, checking again in 15 seconds
Vault Operation: operations/count/a3f96b4a-969a-4ec7-aa8e-937e6449a6eb, Is not done, checking again in 15 seconds
Vault Operation: operations/count/a3f96b4a-969a-4ec7-aa8e-937e6449a6eb, Is not done, checking again in 15 seconds
Getting all Users, may take some time on a large Google Workspace Account...
Got 11029 Users...
Got 11029 Users
Traceback (most recent call last):
  File "__init__.py", line 75827, in ProcessGAMCommand
  File "__init__.py", line 40905, in doPrintVaultCounts
UnboundLocalError: cannot access local variable 'account' where it is not associated with a value
```

**Comment by taers232c** [comment]
Will be fixed shortly. My apologies.
----
Ross Scroggs
***@***.***

**Comment by archierosenblum** [comment]
Thank you very much!

**Comment by taers232c** [comment]
Archie,

What OS are you running on
----
Ross Scroggs
***@***.***

**Comment by taers232c** [comment]
6.80.16 is available.
