### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable when create a VaultMatter

### ISSUE THREAD

**Issue by tissoni** [taers232c/GAMADV-XTD3#443]
Hello, when creating a new Vault Matter with this command:

gam create vaultmatter name "NAME" description "Matter Description" collaborator user@email.com showdetails

Appear this output:

Traceback (most recent call last):
  File "__init__.py", line 76622, in ProcessGAMCommand
  File "__init__.py", line 41157, in doCreateVaultMatter
  File "__init__.py", line 41080, in _showVaultMatter
  File "__init__.py", line 41075, in _cleanVaultMatter
TypeError: argument of type 'NoneType' is not iterable

The vault matter NAME is created in vault.google.com, but i cannot make the export of the data. 

GAMADV-XTD3 7.00.21 - https://github.com/taers232c/GAMADV-XTD3 - pyinstaller
Ross Scroggs <ross.scroggs@gmail.com>
Python 3.13.0 64-bit final
Linux Ubuntu 20.04 Focal Fossa x86_64

**Comment by taers232c** [comment]
It' a bug, I'm fixing it now.

Ross
----
Ross Scroggs
Ross.Scroggs @ gmail.com

**Comment by tissoni** [comment]
Thanks @taers232c !!!

**Comment by taers232c** [comment]
Fixed in 7.00.22

Ross
