### ISSUE TITLE
gam user [userid] check serviceaccount timeout

### ISSUE THREAD

**Issue by jhgarrison** [taers232c/GAMADV-XTD3#448]
I haven't used GAMADV in nearly a year.  2 days ago I upgraded to the current version and everything was working.

Today I tried to "check serviceaccount". It takes a long time (3 minutes or so) and then returns

`ERROR: [Errno 110] Connection timed out`

Nothing has changed on my end and all other Internet traffic seems to be working.

When I interrupted a second attempt I got the following Python traceback, in case it contains a clue:

```
^CTraceback (most recent call last):
  File "__init__.py", line 76757, in ProcessGAMCommand
  File "__init__.py", line 6998, in getEntityToModify
  File "__init__.py", line 5509, in buildGAPIObject
  File "__init__.py", line 4633, in getClientCredentials
  File "google/oauth2/credentials.py", line 409, in refresh
  File "google/oauth2/reauth.py", line 333, in refresh_grant
  File "google/oauth2/_client.py", line 192, in _token_endpoint_request_no_throw
  File "__init__.py", line 4271, in wrapped_request_method
  File "__init__.py", line 4283, in __call__
  File "google_auth_httplib2.py", line 119, in __call__
  File "httplib2/__init__.py", line 1724, in request
  File "httplib2/__init__.py", line 1444, in _request
  File "httplib2/__init__.py", line 1366, in _conn_request
  File "httplib2/__init__.py", line 1156, in connect
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "__main__.py", line 40, in <module>
  File "__main__.py", line 28, in main
  File "__init__.py", line 76796, in ProcessGAMCommand
  File "__init__.py", line 9629, in batchWriteStderr
KeyboardInterrupt
[PYI-157769:ERROR] Failed to execute script '__main__' due to unhandled exception!
```

I'm not sure how to proceed with further troubleshooting

**Comment by taers232c** [comment]
Do: gam checkconn

Send me a Meet/Zoom invitation

ross.scroggs @ gmail.com

**Comment by jhgarrison** [comment]
All URLs confirmed as UP, but when I ran check serviceaccount it required me to re-authorize, even though I just did exactly that 3 days ago.  Everything seems to be working now.
