### ISSUE TITLE
Issue Printing Orgs for ChromeOS Devices

### ISSUE THREAD

**Issue by n3il-a** [taers232c/GAMADV-XTD3#74]
Getting the following error when I try to output a device-count list for our OU's containing ChromeOS Devices.  When running almost the same command (`gam print orgs minusercount 0 todrive`) it outputs the file without issue.

```
$ gam print orgs mincroscount 0 todrive

Getting all Organizational Units, may take some time on a large G Suite Account...
Got 145 Organizational Units
Getting all CrOS Devices for /CompanyName, may take some time on a large Organizational Unit...
Got 0 CrOS Devices...
Getting all CrOS Devices for /CompanyName/Area Contractors, may take some time on a large Organizational Unit...
Got 0 CrOS Devices...
Getting all CrOS Devices for /CompanyName/Business Users , may take some time on a large Organizational Unit...
Traceback (most recent call last):
  File "gam.py", line 4068, in callGAPI
  File "googleapiclient/_helpers.py", line 134, in positional_wrapper
  File "googleapiclient/http.py", line 907, in execute
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://www.googleapis.com/admin/directory/v1/customer/my_customer/devices/chromeos?orgUnitPath=%2FCompanyName%2FBusiness+Users+&fields=nextPageToken%2Cchromeosdevices%28status%29&maxResults=200&prettyPrint=false&alt=json returned "Invalid Input: INVALID_OU_ID">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gam.py", line 12465, in doPrintOrgs
  File "gam.py", line 4087, in callGAPI
gamlib.glgapi.invalidOrgunit: Invalid Input: INVALID_OU_ID

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gam.py", line 46737, in ProcessGAMCommand
  File "gam.py", line 12471, in doPrintOrgs
  File "gam.py", line 537, in checkEntityDNEorAccessErrorExit
  File "gam.py", line 2007, in entityDoesNotExistWarning
  File "gam.py", line 456, in formatKeyValueList
TypeError: can only concatenate str (not "dict") to str
```

**Comment by taers232c** [comment]
I'm fixing the error handling, you need to delete the trailing space from OU "/CompanyName/Business Users "

Ross

**Comment by n3il-a** [comment]
That fixed it, thank you!
