### ISSUE TITLE
formatjson produces invalid JSON

### ISSUE THREAD

**Issue by sreyemnayr** [taers232c/GAMADV-XTD3#86]
```bash
gam calendar room.133@example.com show events singleevents after -1m before +5h fields start,hangoutlink,creator formatjson >> caldata.json
```
Produces `caldata.json`:
```JSON
{"calendarId": "room.133@example.com", "event": {"creator": {"email": "tech@example.com"}, "hangoutLink": "https://meet.google.com/goo-glem-eet", "id": "5vq6bc3fja7ohckfark0t4014u_20200827T131500Z", "start": {"dateTime": "2020-08-27T08:15:00-05:00"}}}
{"calendarId": "room.133@example.com", "event": {"creator": {"email": "ryan.meyers@example.com"}, "hangoutLink": "https://meet.google.com/goo-glem-eet", "id": "7gchvvasmbiendqs995k663il3", "start": {"dateTime": "2020-08-27T11:15:00-05:00"}}}
{"calendarId": "room.133@example.com", "event": {"creator": {"email": "ryan.meyers@example.com"}, "hangoutLink": "https://meet.google.com/goo-glem-eet", "id": "6cc2nmef0854p7vsph699238uq", "start": {"dateTime": "2020-08-27T15:15:00-05:00"}}}
```
That's because it's missing outside brackets and commas between the curly-bracketed objects.
Here's a fixed version `caldatagood.json`
```JSON
[{
		"calendarId": "room.133@example.com",
		"event": {
			"creator": {
				"email": "tech@example.com"
			},
			"hangoutLink": "https://meet.google.com/goo-glem-eet",
			"id": "5vq6bc3fja7ohckfark0t4014u_20200827T131500Z",
			"start": {
				"dateTime": "2020-08-27T08:15:00-05:00"
			}
		}
	},
	{
		"calendarId": "room.133@example.com",
		"event": {
			"creator": {
				"email": "ryan.meyers@example.com"
			},
			"hangoutLink": "https://meet.google.com/goo-glem-eet",
			"id": "7gchvvasmbiendqs995k663il3",
			"start": {
				"dateTime": "2020-08-27T11:15:00-05:00"
			}
		}
	},
	{
		"calendarId": "room.133@example.com",
		"event": {
			"creator": {
				"email": "ryan.meyers@example.com"
			},
			"hangoutLink": "https://meet.google.com/goo-glem-eet",
			"id": "6cc2nmef0854p7vsph699238uq",
			"start": {
				"dateTime": "2020-08-27T15:15:00-05:00"
			}
		}
	}
]
```

The indentation isn't the end of the world, but lacking the square brackets and commas means it isn't consumable.

```Python
# Python throws a JSONDecodeError for the caldata.json

import json
with open('caldata.json') as f:
     data = json.load(f)

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/gam/.pyenv/versions/3.8.2/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/home/gam/.pyenv/versions/3.8.2/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/home/gam/.pyenv/versions/3.8.2/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 252)
```

```Python
# Here's what we actually want (using caldatagood.json)

import json
with open('caldatagood.json') as f:
    data = json.load(f)

print(data)
[{'calendarId': 'room.133@example.com', 'event': {'creator': {'email': 'tech@example.com'}, 'hangoutLink': 'https://meet.google.com/goo-glem-eet', 'id': '5vq6bc3fja7ohckfark0t4014u_20200827T131500Z', 'start': {'dateTime': '2020-08-27T08:15:00-05:00'}}}, {'calendarId': 'room.133@example.com', 'event': {'creator': {'email': 'ryan.meyers@example.com'}, 'hangoutLink': 'https://meet.google.com/goo-glem-eet', 'id': '7gchvvasmbiendqs995k663il3', 'start': {'dateTime': '2020-08-27T11:15:00-05:00'}}}, {'calendarId': 'room.133@example.com', 'event': {'creator': {'email': 'ryan.meyers@example.com'}, 'hangoutLink': 'https://meet.google.com/goo-glem-eet', 'id': '6cc2nmef0854p7vsph699238uq', 'start': {'dateTime': '2020-08-27T15:15:00-05:00'}}}]
```

**Comment by taers232c** [comment]
```
import json
data = []
with open('caldatagood.json') as f:
     for line in f:
          data.append(json.loads(line))
print(data)
```

**Comment by sreyemnayr** [comment]
Yeah I got it working fine with extra processing, just seems like
formatjson should produce valid json is all. I might pick your brain to see
about multiprocessing the code I'm running as a cron job every 5 minutes,
though...that's the point at which my brain kind of explodes from the
chained commands.

**Comment by taers232c** [comment]
Ryan,

The people who originally wanted show with formatjson were reading it with PowerShell and passing it on one line at a time to another app.
No json.load in their world.

Ross
--
ross.scroggs@gmail.com
